Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyModel_CodeFirst.Models;

namespace MyModel_CodeFirst.Controllers
{
    public class BooksController : Controller
    {
        private readonly GuestBookContext _context;

        public BooksController(GuestBookContext context)
        {
            _context = context;
        }

        // GET: Books
        public async Task<IActionResult> Index()
        {
            //2.2.1 改寫Index Action的內容，將留言依新到舊排序
            return View(await _context.Book.OrderByDescending(b=>b.TimeStamp).ThenByDescending(b=>b.GId).ToListAsync());
        }

 

        // GET: Books/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Book.FirstOrDefaultAsync(m => m.GId == id);


            //var rebook = await _context.ReBook.Where(m => m.GId == id).ToListAsync();

            //ViewData["rebook"] = rebook;

            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var book = await _context.Book.FindAsync(id);
            if (book != null)
            {
                _context.Book.Remove(book);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        //2.5.2 在BooksController內增加刪除回覆留言Action
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteReBook(long id)
        {


            var reBook = await _context.ReBook.FindAsync(id);

            if (reBook != null)
            {
                _context.ReBook.Remove(reBook);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Delete", new { id = reBook.GId });
        }

        private bool BookExists(long id)
        {
            return _context.Book.Any(e => e.GId == id);
        }
        //2.3.2 在BooksController內增加讀取照片的方法
        public async Task<FileContentResult> GetImage(long gid)
        {
            var book = await _context.Book.FindAsync(gid);

            if (book == null)
            {
                return null;
            }

            return File(book.Photo, book.ImageType);
        }
    }
}

Controllers/PostBooksController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyModel_CodeFirst.Models;

namespace MyModel_CodeFirst.Controllers
{
    public class PostBooksController : Controller
    {
        private readonly GuestBookContext _context;

        public PostBooksController(GuestBookContext context)
        {
            _context = context;
        }

        //3.1.6 修改Index Action的寫法
        public async Task<IActionResult> Index()
        {
            //var book = await _context.Book.ToListAsync();

            var book = _context.Book.OrderByDescending(b => b.TimeStamp).ThenByDescending(b => b.GId);

            return View(await book.ToListAsync());

            //return View(await _context.Book.ToListAsync());
        }

        // GET: PostBooks/Details/5
        public async Task<IActionResult> Display(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Book
                .FirstOrDefaultAsync(m => m.GId == id);

            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: PostBooks/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PostBooks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Book book, IFormFile? uploadPhoto)
        {
            //上傳照片的處理

            if (uploadPhoto != null)
            {
                if (uploadPhoto.ContentType != "image/jpeg" && uploadPhoto.ContentType != "image/png")
                {
                    ViewData["Message"] = "請上傳jpg或png格式的檔案!!";
                    return View(book);
                }

                //把檔案轉成二進位資料,並放入byte[]
                using (var mem = new MemoryStream())
                {
                    uploadPhoto.CopyTo(mem);

                    book.Photo = mem.ToArray();
                    book.ImageType = uploadPhoto.ContentType;
                }
            }

            book.TimeStamp = DateTime.Now;


            if (ModelState.IsValid)
            {
                _context.Add(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }

        //3.1.5 修改PostBooksController，移除Edit、Delete Action

        private bool BookExists(long id)
        {
            return _context.Book.Any(e => e.GId == id);
        }


        public IActionResult ExceptionTest()
        {
            int a = 0;
            int s = 100 / a;
            return View();
        }
    }
}

Controllers/RePostBooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyModel_CodeFirst.Models;

namespace MyModel_CodeFirst.Controllers
{
    public class RePostBooksController : Controller
    {
        private readonly GuestBookContext _context;

        public RePostBooksController(GuestBookContext context)
        {
            _context = context;
        }

        //3.5.4 修改RePostBooksController，僅保留Create Action，其它全部刪除

        // GET: RePostBooks/Create
        public IActionResult Create(long GId)
        {
            ViewData["GId"] = GId;

            return View();
        }

        // POST: RePostBooks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ReBook reBook)
        {
            reBook.TimeStamp = DateTime.Now;

            if (ModelState.IsValid)
            {
                _context.Add(reBook);
                await _context.SaveChangesAsync();

                //3.5.9 修改RePostBooksController中的Create Action，使其Return JSON資料
                //return RedirectToAction("Display", "PostBooks", new { id=reBook.GId});
                return Json(reBook);
            }

            ViewData["GId"] = new SelectList(_context.Book, "GId", "Author", reBook.GId);
            //3.5.9 修改RePostBooksController中的Create Action，使其Return JSON資料
            //return View(reBook);
            return Json(reBook);
        }


        public IActionResult GetRebookByViewComponent(long? id)
        {
            return ViewComponent("VCReBooks", new { gid = id });
        }
      
    }
}

Views/PostBooks/Create.cshtml
@model MyModel_CodeFirst.Models.Book

@{
    ViewData["Title"] = "我要留言";
}

<h1>@ViewData["Title"]</h1>

<hr />
<div class="row">
    <div class="col-lg-5">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control" rows="6"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Photo" class="control-label"></label>
                <input type="file" name="uploadPhoto" id="uploadPhoto" class="form-control" />
                <span class="text-danger">@ViewData["Message"]</span>
               @*  <input asp-for="Photo" class="form-control" /> *@
              @*   <span asp-validation-for="Photo" class="text-danger"></span> *@
            </div>


            <div class="form-group">
                <label asp-for="Author" class="control-label"></label>
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>

       @*      <div class="form-group">
                <label asp-for="TimeStamp" class="control-label"></label>
                <input asp-for="TimeStamp" class="form-control" />
                <span asp-validation-for="TimeStamp" class="text-danger"></span>
            </div> *@
@* 
            <div class="form-group">
                <label asp-for="ImageType" class="control-label"></label>
                <input asp-for="ImageType" class="form-control" />
                <span asp-validation-for="ImageType" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <input type="submit" value="確定留言" class="btn btn-primary" />
            </div>
        </form>
    </div>
    <div class="col-lg-7" id="photoPreview">

    </div>
</div>

<div>
    <a asp-action="Index">回留言板首頁</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        $('#uploadPhoto').change(function () {
            let file = this.files[0];

            let reader = new FileReader();

            reader.onload = event => {
                $('#photoPreview').html(`<img src="${event.target.result}" width="800" class="img-fluid" />`);
            };
            reader.readAsDataURL(file);
        });
    </script>


}

Views/PostBooks/Display.cshtml
@model MyModel_CodeFirst.Models.Book

@{
    ViewData["Title"] = Model.Title;
}

<h1>@Html.DisplayFor(model => model.Title)</h1>

<div class="card shadow">
    @* //3.3.9 在Display View中加入未上傳照片的留言之顯示方式 *@
    @if (Model.Photo != null)
    {
        <img src="@Url.Action("GetImage","Books",new{gid=Model.GId})
                " class="card-img-top" alt="...">
    }
    <div class="card-body">
        <h3 class="card-title"><strong>@Html.DisplayFor(model => model.Title)</strong></h3>
        @* //3.3.11 在Display View中加入處理「有換行的留言」顯示方式 *@
        <p class="card-text">@Html.Raw(Model.Description.ToString().Replace("\r\n", "<br>"))</p>
        <p class="text-end fs-6">@Html.DisplayFor(model => model.Author) 於 @Html.DisplayFor(model => model.TimeStamp) 發佈</p>
    </div>
</div>
<hr />
@* <a asp-action="Create" asp-controller="RePostBooks" asp-route-GId="@Model.GId" class="btn btn-success btn-lg my-3">我要回覆</a> *@
@* <button class="btn btn-success" onclick="showReForm()">我要回覆</button> *@



@* //3.5.8 配合Boostrap Modal Component顯示出畫面 *@
<!-- Button trigger modal -->
<button type="button" class="btn btn-success mb-3" data-bs-toggle="modal" data-bs-target="#ReFormModal">
    我要回覆
</button>

<!-- Modal -->
<div class="modal fade shadow" id="ReFormModal">
    <div class="modal-dialog modal-xl ">
        <div class="modal-content bg-light">
            <div class="modal-header">
                <h1 class="modal-title fs-3 text-center" id="exampleModalLabel">回覆留言</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="ReForm">
            </div>
            <div class="modal-footer">

                <button type="button" class="btn btn-warning" onclick="ReCreate()">確定回覆</button>
            </div>
        </div>
    </div>
</div>


@* <div id="ReForm" class="p-4 border alert alert-info my-3">
</div>
 *@
 <div id="reBookList">
    @await Component.InvokeAsync("VCReBooks", new { gid = Model.GId })
</div>

<div class="text-end my-3">
    <a asp-action="Index">回留言板首頁</a>
</div>

@*//3.5.7 在PostBooks\Display View中將RePostBooks\Create View以Ajax方式讀入 *@
@section Scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script>
        const ReFormModal = new bootstrap.Modal(document.getElementById('ReFormModal'));
        //3.5.7 在PostBooks\Display View中將RePostBooks\Create View以Ajax方式讀入
        $('#ReForm').load(`/RePostBooks/Create?GId=@(Model.GId)`);

        // $.ajax({
        //     type: "Get",
        //     url: `/RePostBooks/Create?GId=@(Model.GId)`,
        //     success: (data) => {
        //         console.log(data);
        //         $('#ReForm').html(data);
        //     }

        // });

        //3.5.11 在PostBooks\Display View中撰寫相關的JavaScript程式，以Ajax方式執行新增回覆留言
        function ReCreate() {

            console.log($('#reForm').serialize());

            $.ajax({
                type: "Post",
                url: `/RePostBooks/Create`,
                data: $('#reForm').serialize(), //將資料序列化後送出
                success: (data) => {
                    console.log(data);

                    //1.清空表單
                    $('#Description').val('');
                    $('#Author').val('');

                    //2.把Modal視窗關閉
                    
                    ReFormModal.hide();

                    //3.重新讀取回覆留言的資料
                    //重新載入ViewComponent

                    //使用Ajax的方式載入
                    $('#reBookList').load(`/RePostBooks/GetRebookByViewComponent/@(Model.GId)`);

                }
            });

        }


        // function showReForm(){
        //     $('#ReForm').slideToggle(2000);
        // }





    </script>
}

Views/PostBooks/Index.cshtml
@model IEnumerable<MyModel_CodeFirst.Models.Book>

@{
    ViewData["Title"] = "Charming Voices Hub（魅力美音中心）";
}

<h1 class="text-center shadow p-4">@ViewData["Title"]</h1>

<p class="d-grid gap-2">
    <a asp-action="Create" class="btn btn-primary btn-lg">我要留言</a>
</p>

<div class="row">

    @foreach (var item in Model)
    {
        <div class="card shadow mb-4 col-lg-6">
            @* //3.3.8 在Index View中加入未上傳照片的留言之顯示方式 *@
            @if (item.Photo != null)
            {
                <img src="@Url.Action("GetImage","Books",new{gid=item.GId})" class="card-img-top" alt="...">
            }
            <div class="card-body">
                <h3 class="card-title"><strong>@Html.DisplayFor(modelItem => item.Title)</strong></h3>
                @* //3.3.10 在Index View中加入處理「有換行的留言」顯示方式 *@
                <p class="card-text">@Html.Raw(item.Description.ToString().Replace("\r\n","<br>"))</p>

            </div>
            <div class="card-footer">
                <p class="text-end fs-6">
                    @Html.DisplayFor(modelItem => item.Author) 於 @Html.DisplayFor(modelItem => item.TimeStamp) 發佈
                   @*  //3.2.3 修改Index View中Details的超鏈結為Display *@
                    | <a asp-action="Display" asp-route-id="@item.GId">看更多...</a>
                </p>
            </div>
        </div>
    }
</div>
<p class="d-grid gap-2">
    <a asp-action="Create" class="btn btn-primary btn-lg">我要留言</a>
</p>