Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyModel_CodeFirst.Models;

namespace MyModel_CodeFirst.Controllers
{
    public class BooksController : Controller
    {
        private readonly GuestBookContext _context;

        public BooksController(GuestBookContext context)
        {
            _context = context;
        }

        // GET: Books
        public async Task<IActionResult> Index()
        {
            //2.2.1 改寫Index Action的內容，將留言依新到舊排序
            return View(await _context.Book.OrderByDescending(b=>b.TimeStamp).ThenByDescending(b=>b.GId).ToListAsync());
        }

 

        // GET: Books/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Book.FirstOrDefaultAsync(m => m.GId == id);


            //var rebook = await _context.ReBook.Where(m => m.GId == id).ToListAsync();

            //ViewData["rebook"] = rebook;

            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var book = await _context.Book.FindAsync(id);
            if (book != null)
            {
                _context.Book.Remove(book);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        //2.5.2 在BooksController內增加刪除回覆留言Action
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteReBook(long id)
        {


            var reBook = await _context.ReBook.FindAsync(id);

            if (reBook != null)
            {
                _context.ReBook.Remove(reBook);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Delete", new { id = reBook.GId });
        }

        private bool BookExists(long id)
        {
            return _context.Book.Any(e => e.GId == id);
        }
        //2.3.2 在BooksController內增加讀取照片的方法
        public async Task<FileContentResult> GetImage(long gid)
        {
            var book = await _context.Book.FindAsync(gid);

            if (book == null)
            {
                return null;
            }

            return File(book.Photo, book.ImageType);
        }
    }
}

Controllers/PostBooksController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyModel_CodeFirst.Models;

namespace MyModel_CodeFirst.Controllers
{
    public class PostBooksController : Controller
    {
        private readonly GuestBookContext _context;

        public PostBooksController(GuestBookContext context)
        {
            _context = context;
        }

        //3.1.6 修改Index Action的寫法
        public async Task<IActionResult> Index()
        {
            //var book = await _context.Book.ToListAsync();

            var book = _context.Book.OrderByDescending(b => b.TimeStamp).ThenByDescending(b => b.GId);

            return View(await book.ToListAsync());

            //return View(await _context.Book.ToListAsync());
        }

        // GET: PostBooks/Details/5
        public async Task<IActionResult> Display(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Book
                .FirstOrDefaultAsync(m => m.GId == id);

            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: PostBooks/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PostBooks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Book book, IFormFile? uploadPhoto)
        {
            //上傳照片的處理

            if (uploadPhoto != null)
            {
                if (uploadPhoto.ContentType != "image/jpeg" && uploadPhoto.ContentType != "image/png")
                {
                    ViewData["Message"] = "請上傳jpg或png格式的檔案!!";
                    return View(book);
                }

                //把檔案轉成二進位資料,並放入byte[]
                using (var mem = new MemoryStream())
                {
                    uploadPhoto.CopyTo(mem);

                    book.Photo = mem.ToArray();
                    book.ImageType = uploadPhoto.ContentType;
                }
            }

            book.TimeStamp = DateTime.Now;


            if (ModelState.IsValid)
            {
                _context.Add(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }

        //3.1.5 修改PostBooksController，移除Edit、Delete Action

        private bool BookExists(long id)
        {
            return _context.Book.Any(e => e.GId == id);
        }


        public IActionResult ExceptionTest()
        {
            int a = 0;
            int s = 100 / a;
            return View();
        }
    }
}

Views/Home/Index.cshtml
@model IEnumerable<MyModel_CodeFirst.Models.Book>

@{
    ViewData["Title"] = "Home Page";

    string a = "active";

    int i = 0;

}
<div class="background-container">
    <div class="mt-4 p-5 bg-light text-dark shadow rounded jumbottron">
        <h1 class="display-4 text-white textShadow"><strong>Charming Voices Hub（魅力美音中心）留言板</strong></h1>
    <h3 class="text-white textShadow">歡迎光臨本站，請選擇您要的功能</h3>
    <h4 class="text-white ">
        <span class="textShadow">請點我進入留言板</span> <a asp-action="Index" asp-controller="PostBooks" class="btn btn-warning btn-lg">我要留言</a>
    </h4>
</div>
<hr />
</div>

<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
        @for (int j = 0; j < Model.Count(); j++)
        {
           
            a = j == 0 ? "active" : "";

            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="@j" class="@a" aria-current="true" aria-label="Slide 1"></button>
        }
    </div>
    <div class="carousel-inner">

        @foreach (var item in Model)
        {
            a = i == 0 ? "active" : "";

            <div class="carousel-item @a" data-bs-interval="2000">
                <img src="@Url.Action("GetImage","Books",new{gid=item.GId})" class="d-block w-100" alt="...">
            </div>
            i++;
        }
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>